### ISSUE TITLE
Personal-backend manager

### ISSUE THREAD

**Issue by andlo** [OpenVoiceOS/ovos-personal-backend#48]
Is the personal-backend-mannager included in the docker image ? 
If so which port does it use ?
If not - would it be an idea to include it ?

Right now I am just testing to add a personal-backend on a homeassistant as an add-on - and instead of making a new docker i started with the alreddy made docker :)

**Comment by JarbasAl** [comment]
good idea, send a PR updating the Dockerfile :)

**Comment by andlo** [comment]
I will try - I am not that great docker user, but Ill try anyway :)
